# Generated by Django 4.2.7 on 2023-11-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0012_menu_featured"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="guest_number",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="last_name",
        ),
        migrations.AddField(
            model_name="booking",
            name="reservation_date",
            field=models.DateField(default="2020-01-01"),
        ),
        migrations.AddField(
            model_name="booking",
            name="reservation_slot",
            field=models.SmallIntegerField(default=10),
        ),
    ]
